/*
  # Seed All 38 Email Templates

  Populates the database with all 38 professional email templates
  for BioMath Core.
*/

-- Clear existing templates
TRUNCATE email_templates CASCADE;

-- Insert all 38 templates
INSERT INTO email_templates (name, slug, category, subject_en, subject_ru, preview_text, body_en, body_ru, variable_schema, status, description) VALUES
-- ONBOARDING (9)
('Welcome New User', 'welcome_new_user', 'welcome', 'Welcome to BioMath Core', 'Добро пожаловать в BioMath Core', 'Your journey starts here', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;background:#FFF;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;font-size:28px;">Welcome to BioMath Core</h1><p>Hi {{userName}}, we are excited to have you!</p><a href="https://biomathcore.com/dashboard" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;margin:24px 0;">Open Dashboard</a><p style="color:#64748B;margin-top:32px;">© BioMath Core • biomathcore.com</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true}]'::jsonb, 'active', 'Welcome email'),
('Email Verification', 'email_verification', 'welcome', 'Verify your email', 'Подтвердите email', 'Click to verify', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Verify Email</h1><p>Hi {{userName}},</p><a href="{{verifyUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Verify</a><p style="color:#64748B;margin-top:16px;">Code: {{code}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"verifyUrl","type":"string","required":true},{"key":"code","type":"string","required":true}]'::jsonb, 'active', 'Email verification'),
('Magic Link', 'magic_link_signin', 'welcome', 'Sign in link', 'Ссылка для входа', 'Secure sign-in', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Sign In</h1><p>Hi {{userName}},</p><a href="{{magicUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Sign In</a><p style="color:#64748B;">Expires in {{expiresInMin}} min</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"magicUrl","type":"string","required":true},{"key":"expiresInMin","type":"number","required":true}]'::jsonb, 'active', 'Magic link'),
('Password Reset', 'password_reset_requested', 'password_reset', 'Reset password', 'Сброс пароля', 'Reset your password', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Reset Password</h1><p>Hi {{userName}},</p><a href="{{resetUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Reset</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"resetUrl","type":"string","required":true}]'::jsonb, 'active', 'Password reset'),
('Password Confirmed', 'password_reset_confirmed', 'notification', 'Password updated', 'Пароль обновлен', 'Success', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Password Updated</h1><p>Hi {{userName}}, updated at {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', 'Password confirmed'),
('Profile Complete', 'profile_completed', 'notification', 'Profile complete', 'Профиль готов', 'All set', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Complete!</h1><p>Hi {{userName}}, you are all set!</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true}]'::jsonb, 'active', 'Profile complete'),
('Trial Started', 'trial_started', 'billing_invoice', 'Trial started', 'Пробный период', 'Trial active', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Trial Started</h1><p>Hi {{userName}}, {{planName}} trial until {{trialEndsAt}}</p><a href="https://biomathcore.com/dashboard" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Explore</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"trialEndsAt","type":"string","required":true}]'::jsonb, 'active', 'Trial started'),
('Trial Ending', 'trial_ending_reminder', 'billing_invoice', 'Trial ends soon', 'Пробный период истекает', 'Reminder', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Trial Ending</h1><p>Hi {{userName}}, ends {{trialEndsAt}}</p><a href="https://biomathcore.com/pricing" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">View Plans</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"trialEndsAt","type":"string","required":true}]'::jsonb, 'active', 'Trial ending'),
('Trial Ended', 'trial_ended', 'billing_invoice', 'Trial ended', 'Пробный период закончился', 'Subscribe now', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Trial Ended</h1><p>Hi {{userName}}</p><a href="{{plansUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Subscribe</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"plansUrl","type":"string","required":true}]'::jsonb, 'active', 'Trial ended'),

-- BILLING (15)
('Subscription Active', 'subscription_activated', 'payment_success', 'Subscription activated', 'Подписка активна', 'Active now', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Active!</h1><p>Hi {{userName}}, {{planName}} is active</p><p>{{amount}} {{currency}}<br>Next: {{nextBillingAt}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"nextBillingAt","type":"string","required":true}]'::jsonb, 'active', 'Subscription activated'),
('Renewal Upcoming', 'subscription_renewal_upcoming', 'billing_invoice', 'Renewal soon', 'Продление скоро', 'Upcoming', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Renewal</h1><p>Hi {{userName}}, renews {{renewsAt}} for {{amount}} {{currency}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"renewsAt","type":"string","required":true}]'::jsonb, 'active', 'Renewal reminder'),
('Renewed Receipt', 'subscription_renewed_receipt', 'payment_success', 'Receipt', 'Квитанция', 'Payment received', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Renewed</h1><p>Hi {{userName}}, {{planName}} renewed</p><p>{{amount}} {{currency}}</p><a href="{{invoiceUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Invoice</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"invoiceUrl","type":"string","required":true}]'::jsonb, 'active', 'Renewal receipt'),
('Invoice Issued', 'invoice_issued', 'billing_invoice', 'Invoice {{invoiceNumber}}', 'Счет {{invoiceNumber}}', 'New invoice', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Invoice {{invoiceNumber}}</h1><p>Hi {{userName}}</p><p>{{amount}} {{currency}}<br>Due: {{dueAt}}</p><a href="{{invoiceUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">View</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"invoiceNumber","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"invoiceUrl","type":"string","required":true},{"key":"dueAt","type":"string","required":true}]'::jsonb, 'active', 'Invoice issued'),
('Invoice Paid', 'invoice_paid', 'payment_success', 'Payment received', 'Платеж получен', 'Paid', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Paid</h1><p>Hi {{userName}}, invoice {{invoiceNumber}} paid</p><a href="{{receiptUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Receipt</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"invoiceNumber","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"receiptUrl","type":"string","required":true}]'::jsonb, 'active', 'Invoice paid'),
('Payment Failed 1', 'payment_failed_dunning_1', 'payment_failed', 'Payment issue', 'Проблема с оплатой', 'Action needed', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Payment Issue</h1><p>Hi {{userName}}, could not process {{amount}} {{currency}}</p><a href="{{updatePaymentUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Update</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"updatePaymentUrl","type":"string","required":true}]'::jsonb, 'active', 'Payment failed 1'),
('Payment Failed 2', 'payment_failed_dunning_2', 'payment_failed', 'Update payment', 'Обновите оплату', 'Urgent', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Action Required</h1><p>Hi {{userName}}, please update payment</p><a href="{{updatePaymentUrl}}" style="display:inline-block;padding:12px 32px;background:#EF4444;color:#FFF;text-decoration:none;border-radius:6px;">Update Now</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"updatePaymentUrl","type":"string","required":true}]'::jsonb, 'active', 'Payment failed 2'),
('Payment Failed Final', 'payment_failed_final', 'payment_failed', 'Subscription paused', 'Подписка приостановлена', 'Paused', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#EF4444;">Paused</h1><p>Hi {{userName}}</p><a href="{{reactivateUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Reactivate</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"reactivateUrl","type":"string","required":true}]'::jsonb, 'active', 'Payment final'),
('Card Expiring', 'card_expiring', 'billing_invoice', 'Card expiring', 'Карта истекает', 'Update card', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Card Expiring</h1><p>Hi {{userName}}, card {{last4}} expires {{expMonth}}/{{expYear}}</p><a href="{{updatePaymentUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Update</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"last4","type":"string","required":true},{"key":"expMonth","type":"string","required":true},{"key":"expYear","type":"string","required":true},{"key":"updatePaymentUrl","type":"string","required":true}]'::jsonb, 'active', 'Card expiring'),
('Payment Updated', 'payment_method_updated', 'notification', 'Payment updated', 'Оплата обновлена', 'Updated', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Updated</h1><p>Hi {{userName}}, payment ending {{last4}} updated</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"last4","type":"string","required":true}]'::jsonb, 'active', 'Payment updated'),
('Plan Upgraded', 'plan_changed_upgraded', 'subscription_update', 'Upgraded!', 'Обновлен!', 'Plan upgrade', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Upgraded!</h1><p>Hi {{userName}}, now on {{planName}} ({{effectiveAt}})</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"effectiveAt","type":"string","required":true}]'::jsonb, 'active', 'Plan upgraded'),
('Plan Downgraded', 'plan_changed_downgraded', 'subscription_update', 'Plan changed', 'План изменен', 'Plan change', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Plan Changed</h1><p>Hi {{userName}}, changing to {{planName}} on {{effectiveAt}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"planName","type":"string","required":true},{"key":"effectiveAt","type":"string","required":true}]'::jsonb, 'active', 'Plan downgraded'),
('Subscription Canceled', 'subscription_canceled', 'subscription_update', 'Canceled', 'Отменена', 'Cancellation', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Canceled</h1><p>Hi {{userName}}, ends {{cancelAt}}</p><a href="{{feedbackUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Feedback</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"cancelAt","type":"string","required":true},{"key":"feedbackUrl","type":"string","required":true}]'::jsonb, 'active', 'Canceled'),
('Refund Processed', 'refund_processed', 'payment_success', 'Refund processed', 'Возврат обработан', 'Refund', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Refund</h1><p>Hi {{userName}}, {{amount}} {{currency}} refunded for {{invoiceNumber}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"amount","type":"number","required":true},{"key":"currency","type":"string","required":true},{"key":"invoiceNumber","type":"string","required":true}]'::jsonb, 'active', 'Refund'),
('Tax Invoice', 'tax_invoice_available', 'billing_invoice', 'Tax invoice ready', 'Налоговый счет', 'Tax invoice', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Tax Invoice</h1><p>Hi {{userName}}, invoice {{invoiceNumber}}</p><a href="{{invoiceUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Download</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"invoiceNumber","type":"string","required":true},{"key":"invoiceUrl","type":"string","required":true}]'::jsonb, 'active', 'Tax invoice'),

-- SECURITY (8)
('New Device', 'new_device_login', 'notification', 'New sign-in', 'Новый вход', 'Security alert', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">New Sign-In</h1><p>Hi {{userName}}</p><p>Device: {{device}}<br>Location: {{city}}<br>IP: {{ip}}<br>Time: {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"device","type":"string","required":true},{"key":"ip","type":"string","required":true},{"key":"city","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', 'New device'),
('Email Changed', 'email_changed', 'notification', 'Email changed', 'Email изменен', 'Changed', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Email Changed</h1><p>Hi {{userName}}, from {{oldEmail}} to {{newEmail}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"oldEmail","type":"string","required":true},{"key":"newEmail","type":"string","required":true}]'::jsonb, 'active', 'Email changed'),
('Password Changed', 'password_changed', 'notification', 'Password changed', 'Пароль изменен', 'Changed', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">Password Changed</h1><p>Hi {{userName}}, at {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', 'Password changed'),
('2FA Enabled', 'twofa_enabled', 'notification', '2FA enabled', '2FA включена', 'Enabled', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#10B981;">2FA Enabled</h1><p>Hi {{userName}}, at {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', '2FA enabled'),
('2FA Disabled', 'twofa_disabled', 'notification', '2FA disabled', '2FA отключена', 'Disabled', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">2FA Disabled</h1><p>Hi {{userName}}, at {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', '2FA disabled'),
('Data Export', 'data_export_ready', 'general', 'Data export ready', 'Экспорт готов', 'Download', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Data Export</h1><p>Hi {{userName}}, expires {{expiresAt}}</p><a href="{{downloadUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Download</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"downloadUrl","type":"string","required":true},{"key":"expiresAt","type":"string","required":true}]'::jsonb, 'active', 'Data export'),
('Deletion Scheduled', 'account_deletion_scheduled', 'general', 'Deletion scheduled', 'Удаление запланировано', 'Warning', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#EF4444;">Deletion Scheduled</h1><p>Hi {{userName}}, on {{scheduledAt}}</p><a href="{{cancelDeletionUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Cancel</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"scheduledAt","type":"string","required":true},{"key":"cancelDeletionUrl","type":"string","required":true}]'::jsonb, 'active', 'Deletion scheduled'),
('Account Deleted', 'account_deleted', 'general', 'Account deleted', 'Аккаунт удален', 'Deleted', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Deleted</h1><p>Hi {{userName}}, deleted {{time}}</p></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"time","type":"string","required":true}]'::jsonb, 'active', 'Account deleted'),

-- ENGAGEMENT (4)
('Weekly Digest', 'weekly_digest', 'promotion', 'Weekly digest', 'Еженедельный дайджест', 'Summary', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">Weekly Digest</h1><p>Hi {{userName}}</p><a href="https://biomathcore.com/dashboard" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Dashboard</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true}]'::jsonb, 'active', 'Weekly digest'),
('Feature Announcement', 'feature_announcement', 'promotion', 'New: {{featureName}}', 'Новое: {{featureName}}', 'New feature', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">New: {{featureName}}</h1><p>Hi {{userName}}</p><a href="{{changelogUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Learn More</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"featureName","type":"string","required":true},{"key":"changelogUrl","type":"string","required":true}]'::jsonb, 'active', 'Feature announce'),
('NPS Survey', 'nps_survey', 'general', 'Quick feedback', 'Быстрый опрос', 'Survey', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Feedback</h1><p>Hi {{userName}}</p><a href="{{surveyUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Survey (1 min)</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"surveyUrl","type":"string","required":true}]'::jsonb, 'active', 'NPS survey'),
('Winback', 'reactivation_winback', 'promotion', 'Come back!', 'Вернитесь!', 'We miss you', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#2563EB;">We Miss You!</h1><p>Hi {{userName}}</p><a href="{{comebackUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Return</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"comebackUrl","type":"string","required":true}]'::jsonb, 'active', 'Winback'),

-- OPS (2)
('Maintenance', 'maintenance_notice', 'notification', 'Maintenance {{window}}', 'Обслуживание {{window}}', 'Scheduled', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1 style="color:#F59E0B;">Maintenance</h1><p>Hi {{userName}}, during {{window}}</p><a href="{{detailsUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Details</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"window","type":"string","required":true},{"key":"detailsUrl","type":"string","required":true}]'::jsonb, 'active', 'Maintenance'),
('Incident', 'incident_postmortem', 'notification', 'Incident report', 'Отчет об инциденте', 'Report', '<!DOCTYPE html><html><body style="font-family:Inter,sans-serif;"><div style="max-width:600px;margin:0 auto;padding:40px;"><h1>Incident Report</h1><p>Hi {{userName}}</p><a href="{{summaryUrl}}" style="display:inline-block;padding:12px 32px;background:#2563EB;color:#FFF;text-decoration:none;border-radius:6px;">Read Report</a></div></body></html>', NULL, '[{"key":"userName","type":"string","required":true},{"key":"summaryUrl","type":"string","required":true}]'::jsonb, 'active', 'Incident');

-- Verify
SELECT COUNT(*) as total FROM email_templates;
